site: Ultimate. RnD Blog

url: https://rnd.ultimate.ai
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

compress_html:
  clippings: []
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
