basic_settings:
  site_title: Ultimate.ai Tech Blog
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/logo.svg
  logo_image_dark_mode: /assets/img/brand/logo_white.svg
  mobile_logo_image: /assets/img/brand/logo.svg
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: basic
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons:
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket.
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work!
menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/blog'
    - title: 'About Us'
      url: '/about'
    - title: 'Careers'
      url: '/careers'

footer_settings:
  footer_tagline: Argon & Jekyll, together at last.

contact_settings:
  form_action: '/contact'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  github_url: 'https://github.com/ultimateai'
  linkedin_url: 'https://www.linkedin.com/company/ultimate.ai/mycompany/'
  facebook_url: ''
  twitter_url: 'https://twitter.com/ultiai'
  instagram_url: ''
  youtube_url: 'https://www.youtube.com/channel/UCG5VvY2B3_au8MQffPfClow'
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  reddit_url: ''


authors:
  andras:
    name: András Beke
    role: Senior AI Researcher
    picture: /assets/img/faces/faces_andras.jpeg
  demo:
    name: Demo Author
    role: Role in the Company
    picture: /assets/img/faces/faces_demo.png
  mohamed:
    name: Mohamed Abdelazim
    role: Senior Backend Engineer
    picture: /assets/img/faces/faces_mohamed.jpeg
  simon:
    name: Simon Munch-Andersen
    role: Chief Technology Officer
    picture: /assets/img/faces/faces_simon.jpeg

advanced_settings:
  analytics_code:
  header_js:
  footer_js:
